### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ExaSonit** [BlackLight-NL/BlackLight#14]
Branch: Master
Error: Argument 2 passed to pocketmine\level\generator\biome\BiomeSelector::__construct() must be callable, object given, called in C:\Users\User\Downloads\PocketMine-MP\1b\src\pocketmine\level\generator\normal\Normal.php on line 133
File: /src/pocketmine/level/generator/biome/BiomeSelector
Line: 44 
It causes a crashdump

**Comment by caspervanneck** [comment]
you shuld go to this https://github.com/BlackLight-NL/BlackMine not here this is fore testing

**Comment by ExaSonit** [comment]
oh well... i should re-add redstone files
