### ISSUE TITLE
Should we add a discord?

### ISSUE THREAD

**Issue by Fabiansigala** [BlackLight-NL/BlackLight#16]
@caspervanneck should we add a discord I can make us one?

**Comment by caspervanneck** [comment]
yes @Fabiansigala am tinkin to make owner 🥇

**Comment by Fabiansigala** [comment]
@caspervanneck 👍

**Comment by Fabiansigala** [comment]
@caspervanneck ok I will create it

**Comment by Fabiansigala** [comment]
@caspervanneck or will you?

**Comment by caspervanneck** [comment]
do you create i no time now

**Comment by Fabiansigala** [comment]
Ok I will

**Comment by caspervanneck** [comment]
@Fabiansigala your now owner (the full team)

**Comment by caspervanneck** [comment]
@Fabiansigala you may update blackmine instead of this one it wont get 1.1 update

**Comment by Fabiansigala** [comment]
Ok

**Comment by Fabiansigala** [comment]
@caspervanneck oh and here https://discord.gg/9pTmemr
